version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "java application build"
      - aws --version
      - echo logging to AWS ECR 
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | cut -d":" -f2)
      - echo IMAGE_TAG = $IMAGE_TAG
      - IMAGE_REPO_NAME=bhesh-demo-ecr
  build:
    commands:
      - echo Build started on `date`
      - echo Creating artifacts
      - mvn clean package
      - echo Building the Docker image...
      - echo "docker build -t $IMAGE_REPO_NAME ."
      - docker build -t bhesh-demo-ecr .
      - docker tag bhesh-demo-ecr:latest 797013890234.dkr.ecr.us-east-1.amazonaws.com/bhesh-demo-ecr:v1
  post_build:
    commands:
      - echo Build complated on `date`
      - echo Pushing the Docker image
      - docker push 797013890234.dkr.ecr.us-east-1.amazonaws.com/bhesh-demo-ecr:v1
      - echo Done!!
