version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "java application build"
      - aws --version
      - echo logging to AWS ECR 
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo ecr repository URL $ECR_REPOSITORY_URL
      - echo printing CODEBUILD_RESOLVED_SOURCE_VERSION =  $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo pringing CODEBUILD_BUILD_ID = $CODEBUILD_BUILD_ID
      - echo printing CODEBUILD_RESOLVED_SOURCE_VERSION = $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo code commit hash = $COMMIT_HASH
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | cut -d":" -f2)
      - echo IMAGE_TAG = $IMAGE_TAG
      - IMAGE_REPO_NAME=bhesh-demo-ecr
  build:
    commands:
      - echo Build started on `date`
      - echo Creating artifacts
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build complated on `date`
      - echo Pushing the Docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Writing image definition file..
      - printf '[{"name":"spring_boot_test_app", "imageUri":"%s"}]' $ECR_REPOSITORY_URL:$IMAGE_TAG > imagedefination.json
      - cat imagedefination.json
