
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema
    username: frauduser
    password: fraudpw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true