---
spring:
  datasource:
    url: jdbc:h2:file:/Users/bsejawal/Desktop/java/crud/src/main/resources/data/testdb
    driverClassName: org.h2.Driver
    username: a
    password: a
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
#server.servlet.contextPath=/api